name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: johnlockwood
  GITHUB_REPOSITORY: johnlockwood/johnlockwood.github.io
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: 
  push:
    branches: [ sphinx ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: codesolid/johnlockwood_com

    steps:
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: |
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git#sphinx" 
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: "/home/runner/work/johnlockwood.github.io/johnlockwood.github.io/scripts/buildsite.sh"
        shell: bash