name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: johnlockwood
  GITHUB_REPOSITORY: johnlockwood/johnlockwood.github.io
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: 
  push:
    branches: [ sphinx ]

jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: codesolid/johnlockwood_com

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'sphinx'

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: sphinx-build "${GITHUB_WORKSPACE}/src" "${GITHUB_WORKSPACE}/docs"
        shell: bash
        
      - uses: actions/upload-pages-artifact@v2
